### PR TITLE
make PyPi Repository work with Simple API

### PR DESCRIPTION
**Pull request by ffung**
tested it on pypi.org 

local nexus as follows
```
jython {
  // Replace all repositories with this one
  sourceRepositories = []
  // Add another repository to the existing ones
  repository new com.hierynomus.gradle.plugins.jython.repository.PypiRepository('http://192.168.99.100:32769/repository/ORG-PYTHON-proxy/simple/${dep.name}/')
}
```

### CODE REVIEW

**Comment by ffung** [comment]
Fixes #22

**Comment by ffung** [comment]
I think the build fails bc of openjdk not supporting certain crypto providers anymore, see https://github.com/travis-ci/travis-ci/issues/8503#issuecomment-339943812

Can we bump travis to use openjdk8?
https://github.com/gradle/gradle/issues/2421#issuecomment-326755308

**Comment by hierynomus** [comment]
Hi Fai,

Just did some reading up. The `simple` API is a legacy one and is discouraged on pypi.org. I would suggest to keep the current JSON one as is, and define a new `PypiLegacyRepository` that supports the `simple` API. 

Makes sense?

**Comment by ffung** [comment]
Yes, sounds reasonable, will do.

**Comment by ffung** [comment]
@hierynomus done ;-)

**Comment by ffung** [comment]
thanks! 
@hierynomus can you also roll up a release for me ;-)

**Comment by hierynomus** [comment]
DOne!

**Pull request merged**
